#!/usr/bin/env python3
"""H73 — ATTACK on the loop (§12.8): one lane's UNCOMMITTED, UNFINISHED edit
freezes every other lane's commits, and the gate's own header says it cannot.

TARGET: `spikes/harness/pre-commit.hook` v2, and specifically the two sentences
that decided F2 would be documented rather than fixed.

WHAT HAPPENED, BEFORE ANY PROBE WAS WRITTEN
--------------------------------------------
At ~17:0x AGENT-1 held two finished, green, unrelated cycles for twenty minutes.
`refcheck.py` refused on:

    UNRESOLVED spikes/harness/test_loop_gate.sh: `spikes/H61_lock_handoff/RESULT.md` does not exist

That citation is in **another lane's 83 uncommitted lines** -- `git show
HEAD:spikes/harness/test_loop_gate.sh | grep -c` returns **0**, the worktree
returns **1** -- and the file it cites is the RESULT.md of a spike ok-1 had
CLAIMed and was still running. Logged in `BLOCKED.log` as it happened.

THE TWO CLAIMS UNDER ATTACK, quoted from the hook's own v2 header
------------------------------------------------------------------
  (1) "for `refcheck.py` and `journalcheck.py` this is a gate on the state of
       the shared documents in the tree, WHICH ANY LANE CAN TRIP AND ANY LANE
       CAN CLEAR."
  (2) "With no backlog, a refusal can only mean the commit in front of it
       introduced something."

And the upgrade path the file names for itself:
  (3) "If a backlog ever accumulates, the upgrade is to compare against HEAD and
       refuse only on new items."

THE FALSIFIER, STATED BEFORE THE RUN AND FIXED IN THIS FILE
------------------------------------------------------------
    If the refusal that blocks lane A is reachable from lane A's own commit --
    that is, if scoping the checker to the paths the commit carries would still
    refuse it -- then the gate IS judging lane A's commit, claim (1) stands, and
    this attack is wrong.

It fires if a commit carrying none of the offending paths is refused, AND the
path-scoped verdict on the same commit is ACCEPT.

WHY A SYNTHETIC ROOT AND NOT THE LIVE TREE
-------------------------------------------
The live observation above is real and is quoted, but it is NOT the evidence:
the tree went green when ok-1 landed its file, so the state is gone and an
attack whose evidence cannot be re-run is an anecdote. `refcheck.ROOT` is
derived from `__file__`, so a synthetic root with the module copied into
`spikes/harness/` is judged as its own repo. Everything below runs there.

The synthetic root is created INSIDE the workspace (§10: nothing outside the
workspace is written) and removed at exit.

  python3 probe.py
"""
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
HARNESS_SRC = os.path.join(ROOT, 'spikes', 'harness')
SCRATCH = os.path.join(HERE, 'scratch')          # inside the workspace, per §10
PINNED = {}   # rel -> HEAD blob sha of the instrument actually run

# refcheck refuses a HARNESS entry that is not on disk (v3), so the synthetic
# root carries every one of them as a stub. Stubs, not copies: a copy of the
# real MISSION_LOOP.md would drag in every citation it makes and the probe would
# be measuring this repo's contents instead of the gate's scope.
#
# The stub MISSION_LOOP and GUARDRAILS define a SUPERSET of the sections and
# guardrails the copied modules cite. `C_baseline_is_green` refused two runs of
# this probe before they did: the modules cite §12.2, §13.3, A28 and twenty
# others, none of which a two-section stub defines, so the baseline was red and
# every refusal below it would have been about the copies rather than about lane
# B's edit. Generated by range rather than by hand, because hand-listing them is
# how the second run still came back red.
_ML = ('# MISSION LOOP\n\n'
       + ''.join(f'## {n} · section {n}\n\n' for n in range(1, 21))
       + ''.join(f'- **12.{n} · bullet {n}.** text\n' for n in range(1, 21)))
_GR = ('# guardrails\n\n'
       + ''.join(f'### A{n}\nguardrail {n}\n\n' for n in range(1, 41)))

STUBS = {
    'MISSION_LOOP.md': _ML,
    'CLAUDE.md': '# discipline\n',
    'WORK_QUEUE.md': '# queue\n\n| id | what | status |\n|---|---|---|\n'
                     '| H1 | a row | OPEN |\n',
    'HANDOFF.md': '# HANDOFF\n',
    'analysis/GUARDRAILS.md': _GR,
    'run_loop.sh': '#!/bin/sh\n# launcher\n',
    '.claude/hooks/loop_gate.sh': '#!/bin/sh\n# gate\n',
    '.claude/settings.json': '{}\n',
}


def sh(cwd, *args, **kw):
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True, **kw)


def build_root(d):
    """A minimal repo that `refcheck.py` judges as its own harness."""
    for rel, body in STUBS.items():
        p = os.path.join(d, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, 'w', encoding='utf-8') as f:
            f.write(body)
    # PINNED TO HEAD, NOT COPIED FROM THE WORKTREE, and `certify` is what forced
    # it: the first version used `shutil.copy2` from `spikes/harness/` and
    # certify REFUSED with `DIRTY TREE spikes/harness at cf9f5a29: 2 modified`.
    # Those two modifications are other lanes' in-flight edits -- one of them to
    # `refcheck.py`, the instrument this probe runs. Measuring the gate through a
    # copy of an uncommitted edit would have described a gate that exists in no
    # commit (A24, family C), in a spike whose entire subject is other lanes'
    # uncommitted edits. The blob hashes are recorded in the artifact.
    os.makedirs(os.path.join(d, 'spikes', 'harness'), exist_ok=True)
    PINNED.clear()
    for fn in ('refcheck.py', 'journalcheck.py', 'githygiene.py',
               'pre-commit.hook', 'commit-msg.hook'):
        rel = f'spikes/harness/{fn}'
        blob = sh(ROOT, 'git', 'show', f'HEAD:{rel}').stdout
        dst = os.path.join(d, 'spikes', 'harness', fn)
        with open(dst, 'w', encoding='utf-8') as f:
            f.write(blob)
        os.chmod(dst, 0o755)
        PINNED[rel] = sh(ROOT, 'git', 'rev-parse', f'HEAD:{rel}').stdout.strip()
    # A per-lane brief, because `prompts/*.md` is where `## 0 ·` is DEFINED in
    # this repo (`prompts/AGENT-1.md:18`) and `refcheck.py` cites §0 in a comment.
    # refcheck v3 hands brief sections out per file rather than unioning them, so
    # without a brief on disk §0 resolves nowhere and the baseline stays red --
    # the third thing `C_baseline_is_green` caught.
    os.makedirs(os.path.join(d, 'prompts'), exist_ok=True)
    with open(os.path.join(d, 'prompts', 'LANE-A.md'), 'w') as f:
        f.write('# LANE-A brief\n\n## 0 · Claim your identity\n\ntext\n')

    # lane A's own file, and lane B's file. Neither cites anything yet.
    for name in ('lane_a.md', 'lane_b.md'):
        with open(os.path.join(d, 'spikes', 'harness', name), 'w') as f:
            f.write('# nothing cited here\n')
    # MATERIALISE WHATEVER THE COPIED MODULES CITE, so the baseline resolves.
    # `C_baseline_is_green` REFUSED THE FIRST RUN of this probe without this
    # block: refcheck.py, journalcheck.py and githygiene.py cite real paths in
    # the real repo, none of which exist in a synthetic root, so the baseline was
    # already red and every refusal measured below would have been about the
    # copies rather than about lane B's edit. The control caught it; the fix is
    # to clean the baseline, not to loosen the control.
    #
    # This runs BEFORE lane B's citation is written, so it cannot materialise
    # the path whose absence is the whole measurement.
    for _ in range(6):
        _rc, out = refcheck_rc(d)
        missing = set()
        for line in out.splitlines():
            if 'UNRESOLVED' in line and '`' in line:
                missing.add(line.split('`')[1])
        if not missing:
            break
        for rel in missing:
            p = os.path.join(d, rel)
            os.makedirs(os.path.dirname(p), exist_ok=True)
            open(p, 'a').close()

    sh(d, 'git', 'init', '-q')
    sh(d, 'git', 'config', 'user.email', 't@t')
    sh(d, 'git', 'config', 'user.name', 't')
    sh(d, 'git', 'add', '-A')
    sh(d, 'git', 'commit', '-q', '-m', 'baseline: the harness resolves cleanly')
    hook = os.path.join(d, '.git', 'hooks', 'pre-commit')
    shutil.copy2(os.path.join(d, 'spikes', 'harness', 'pre-commit.hook'), hook)
    os.chmod(hook, 0o755)
    return d


def refcheck_rc(d):
    r = sh(d, sys.executable, os.path.join(d, 'spikes', 'harness', 'refcheck.py'))
    return r.returncode, r.stdout + r.stderr


def unresolved_files(out):
    """The FILE each unresolved citation lives in -- the attribution a scoped
    gate would filter on."""
    files = set()
    for line in out.splitlines():
        if 'UNRESOLVED' in line:
            rest = line.split('UNRESOLVED', 1)[1].strip()
            files.add(rest.split(':', 1)[0].strip())
    return files


def commit_of(d, *paths):
    """`git commit --only` the given paths, hook live. Returns (rc, output)."""
    r = sh(d, 'git', 'commit', '--only', *paths, '-m',
           'S1: a finding was recorded here')
    return r.returncode, r.stdout + r.stderr


def main():
    if os.path.exists(SCRATCH):
        shutil.rmtree(SCRATCH)
    os.makedirs(SCRATCH)
    results = {}
    try:
        d = build_root(SCRATCH)

        rc0, out0 = refcheck_rc(d)
        results['baseline_refcheck_green'] = (rc0 == 0)

        # ---- lane B: an UNCOMMITTED edit adding a citation to a file that does
        #      not exist yet, exactly ok-1's shape (the RESULT.md was coming).
        with open(os.path.join(d, 'spikes', 'harness', 'lane_b.md'), 'w') as f:
            f.write('# lane B mid-cycle\n\nEvidence: `spikes/H99_not_yet/RESULT.md`.\n')

        rc1, out1 = refcheck_rc(d)
        offending = unresolved_files(out1)
        results['lane_b_edit_makes_refcheck_refuse'] = (rc1 != 0)
        results['offending_files'] = sorted(offending)

        # ---- lane A: an unrelated, complete, correct commit of its OWN file.
        with open(os.path.join(d, 'spikes', 'harness', 'lane_a.md'), 'w') as f:
            f.write('# lane A finished a cycle\n\nNothing is cited here.\n')
        rcA, outA = commit_of(d, 'spikes/harness/lane_a.md')
        results['lane_a_commit_refused'] = (rcA != 0)
        carried = {'spikes/harness/lane_a.md'}
        results['lane_a_carried_paths'] = sorted(carried)

        # THE SET DIFFERENCE THAT DECIDES IT: is any offending file among the
        # paths lane A is committing?
        results['offending_in_lane_a_commit'] = sorted(offending & carried)
        results['scoped_gate_would_accept'] = not (offending & carried)

        # ---- (3) WOULD THE FILE'S OWN NAMED UPGRADE HAVE HELPED? Compare the
        #      offending content against HEAD, which is what "compare against
        #      HEAD and refuse only on new items" means.
        head = sh(d, 'git', 'show', 'HEAD:spikes/harness/lane_b.md').stdout
        results['violation_present_in_HEAD'] = ('H99_not_yet' in head)
        results['head_baseline_would_still_refuse'] = not results['violation_present_in_HEAD']

        # ---- THE H27 CASE THE HEADER PROTECTS, and the reason it refuses to
        #      scope: a lane committing the file that CARRIES the violation must
        #      still be refused, or scoping would be a weakening (§10).
        with open(os.path.join(d, 'spikes', 'harness', 'lane_a.md'), 'w') as f:
            f.write('# lane A\n\nEvidence: `spikes/H98_also_missing/RESULT.md`.\n')
        rc2, out2 = refcheck_rc(d)
        off2 = unresolved_files(out2)
        carried2 = {'spikes/harness/lane_a.md'}
        results['h27_case_offending'] = sorted(off2)
        results['h27_case_scoped_gate_refuses'] = bool(off2 & carried2)
        rc3, out3 = commit_of(d, 'spikes/harness/lane_a.md')
        results['h27_case_current_gate_refuses'] = (rc3 != 0)
    finally:
        shutil.rmtree(SCRATCH, ignore_errors=True)

    fired = (results.get('lane_a_commit_refused') and
             results.get('scoped_gate_would_accept'))
    results['falsifier_fired'] = bool(fired)
    results['pinned_instruments_HEAD_blobs'] = dict(PINNED)

    print('=' * 72)
    for k in sorted(results):
        print(f'  {k:42s} {results[k]}')
    print('=' * 72)

    checks = [
        ('C_baseline_is_green',
         results['baseline_refcheck_green'],
         'the synthetic harness must resolve cleanly BEFORE lane B edits it, or '
         'every refusal below is about the stubs rather than about the edit'),
        ('C_lane_b_edit_is_what_refuses',
         results['lane_b_edit_makes_refcheck_refuse'],
         'lane B\'s uncommitted edit must be what turns refcheck red -- this is '
         'the null: if it were red anyway, nothing is being demonstrated'),
        ('C_lane_a_commit_carries_none_of_it',
         not results['offending_in_lane_a_commit'],
         'the offending file must NOT be among the paths lane A commits, or the '
         'gate is judging lane A\'s commit exactly as its header claims'),
        ('C_scoping_still_catches_the_H27_CASE',
         results['h27_case_scoped_gate_refuses'] and
         results['h27_case_current_gate_refuses'],
         'a lane committing the file that CARRIES the dangling citation must be '
         'refused under BOTH gates, or the proposed scoping is a weakening (§10) '
         'rather than a narrowing'),
    ]
    bad = [n for n, ok, _ in checks if not ok]
    for n, ok, why in checks:
        print(f'  {"FIRES" if ok else "DID NOT FIRE"}  {n}\n      {why}')
    print()
    print(f'falsifier F_refusal_is_reachable_from_the_commit: '
          f'{"FIRED" if fired else "did not fire"}')

    with open(os.path.join(HERE, 'gate_scope.json'), 'w') as f:
        json.dump(results, f, indent=2, sort_keys=True)

    sys.path.insert(0, os.path.join(ROOT, 'spikes', 'harness'))
    from kfcheck import certify
    from provenance import Control, Falsifier

    WHY = {
        'C_baseline_is_green':
            'a null that cannot be clean cannot contain the effect (A20)',
        'C_lane_b_edit_is_what_refuses':
            "lane B's uncommitted edit must be what turns refcheck red",
        'C_lane_a_commit_carries_none_of_it':
            "the offending file must not be among lane A's committed paths",
        'C_scoping_still_catches_the_H27_CASE':
            'the proposed narrowing must still refuse the case the header '
            'protects, or it is a weakening (§10) rather than a narrowing',
    }
    CANFAIL = {
        'C_baseline_is_green': 'any citation unresolved before lane B edits',
        'C_lane_b_edit_is_what_refuses': 'refcheck staying green after the edit',
        'C_lane_a_commit_carries_none_of_it':
            'the offending path appearing in the commit',
        'C_scoping_still_catches_the_H27_CASE':
            'either gate accepting a commit of the file carrying the citation',
    }
    C = []
    for name, ok, why in checks:
        c = Control(name, WHY[name],
                    null_must_contain=why,
                    can_fail_because=CANFAIL[name])
        c.observe(bool(ok), results)
        C.append(c)

    F = Falsifier('F_refusal_is_reachable_from_the_commit',
                  refutes='this attack: if scoping the checkers to the paths the '
                          'commit carries would still refuse lane A, the gate is '
                          "judging lane A's commit and its header stands",
                  fires_when='lane A is refused while carrying none of the '
                             'offending paths, and the scoped verdict is ACCEPT',
                  null_must_contain='a commit whose own paths carry the dangling '
                                    'citation, which both gates refuse — measured '
                                    'here as the H27 case')
    F.observe(bool(fired), results)

    ok, problems = certify(
        HERE, deps=[],
        no_deps_reason='the instruments are BYTE-PINNED to HEAD blobs inside the '
                       'probe (recorded in gate_scope.json) rather than read from '
                       'spikes/harness, which carries two other lanes\' in-flight '
                       'edits -- one of them to refcheck.py, the module this probe '
                       'runs. A dep-directory staleness check would be judging '
                       'their work rather than this run\'s inputs.',
        artifacts=[os.path.join(HERE, 'gate_scope.json')],
        controls=C, falsifiers=[F],
        falsifier='a path-scoped gate also refusing lane A, which would put the '
                  'refusal inside lane A\'s own commit and leave the hook\'s '
                  '"any lane can clear" reading intact')
    print('certify ok=%s' % ok)
    for p in problems:
        print('  PROBLEM', p)
    if bad or not ok:
        print(f'VOID — controls did not fire: {", ".join(bad)}' if bad else '')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
